<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Lacuri din Romania')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/colorbox.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-alert.js')
            ->prependFile($this->basePath() . '/js/bootstrap-button.js')
            ->prependFile($this->basePath() . '/js/bootstrap-carousel.js')
            ->prependFile($this->basePath() . '/js/bootstrap-collapse.js')
            ->prependFile($this->basePath() . '/js/bootstrap-dropdown.js')
            ->prependFile($this->basePath() . '/js/bootstrap-modal.js')
            ->prependFile($this->basePath() . '/js/bootstrap-popover.js')
            ->prependFile($this->basePath() . '/js/bootstrap-scrollspy.js')
            ->prependFile($this->basePath() . '/js/bootstrap-tab.js')
            ->prependFile($this->basePath() . '/js/bootstrap-tooltip.js')
            ->prependFile($this->basePath() . '/js/bootstrap-transition.js')
            ->prependFile($this->basePath() . '/js/bootstrap-typehead.js')
            ->prependFile($this->basePath() . 'http://maps.googleapis.com/maps/api/js?sensor=false')
            ->prependFile($this->basePath() . '/js/gmap3.min.js')
            ->prependFile($this->basePath() . '/js/jquery.colorbox-min.js.js')
            ->prependFile($this->basePath() . '/js/proper.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div id="wrapper">
            <div id="breadcrumb-wrapper">
                <div class="container">
                    <div class="pull-left">Joi, 30.01.2014</div>
                    <div class="pull-right">
                        <a href="#">Log In</a>
                        <a href="#">Sign Up</a>
                    </div>
                </div>
            </div>
                        <!-- start header-wrapper -->
            <div id="header-wrapper">
                <div class="container">
                    <div class="panel">
                        <div class="row-fluid">
                            <div class="span9 right-line">
                                <a class="brand" href="#"><h1 class="font-caly"><img src="proper_theme/images/logo.png" width="40" alt="logo" /> Lacuri <small class="visible-desktop visible-tablet">din Romania</small></h1></a>
                            </div>
                            <div class="span3 ">
                                <div class="clearfix">
                                    
                                    <form method="get" class="form-search" />
                                        <div class="input-append">
                                            <input title="Keywords." class="search-query form-text input-block-level" placeholder="Cautare" type="text" name="" />
                                            <button type="submit" class="btn"><i class="icon-search"></i></button>
                                        </div><!-- /.input-append -->
                                    </form>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
            </div><!-- End header-wrapper -->
            <!-- start Navigation -->
            <div id="navigation">
                <div class="container">
                    <div class="navbar navbar-inverse">
                        <div class="navbar-inner">
                            <div class="container">
                                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <span class="brand visible-phone visible-tablet">Navbar</span>
                                <!--.nav-collapse -->
                                <div class="nav-collapse collapse">
                                    <ul class="nav">
                                        <li class="dropdown active">
                                            <a href="#" >Home</a>
                                            
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lacuri <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Lacuri naturale</a></li>
                                                <li><a href="#">Lacuri artificiale</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Balti de pescuit</a></li>
                                        <li><a href="#">Pensiuni</a></li>
                                        <li><a href="contact.html">Contact</a></li>
                                    </ul>
                                   

                                </div><!--/.nav-collapse -->
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Navigation -->
            <div id="content">
                <?php echo $this->content; ?>
            </div>
            <!-- start Footer -->
            <div id="footer-wrapper">
                <!-- start footer-ribon -->
                <div class="container">
                    <div class="footer-ribon">
                        <span>Get in Touch</span>
                    </div>
                </div><!-- end footer-ribon -->
                <div id="footer-top">
                    <div class="container">
                        <div class="row-fluid">
                            <div class="span3">
                                <div class="panel">
                                    <h4><i class="icon-time"></i> Contact</h4>
                                    <p>Nullam justo nunc, dignissim at convallis posuere, sodales eu orci.</p>
                                    <ul class="unstyled">
                                        <li><i class="icon-home"></i> 123, Los Angeles, CA, 54321</li>
                                        <li><i class="icon-phone"></i> +239-3823-3434</li>
                                        <li><i class="icon-envelope"></i> someone@company.com</li>
                                    </ul>


                                    <a href="#" class="btn-proper btn"><i class="icon-facebook"></i></a>
                                    <a href="#" class="btn-proper btn"><i class="icon-twitter"></i></a>
                                    <a href="#" class="btn-proper btn"><i class="icon-google-plus"></i></a>
                                    <a href="#" class="btn-proper btn"><i class="icon-pinterest"></i></a>


                                </div>
                            </div>
                            <div class="span3">
                                <div class="panel">
                                    <h4><i class="icon-suitcase"> </i> Pages Link</h4>
                                    <ul class="unstyled list-link">
                                        <li><a href="#">Condimentum - Condimentum gravida</a></li>
                                        <li><a href="#">Etiam at - Condimentum gravida</a></li>
                                        <li><a href="#">Fusce vel - Condimentum gravida</a></li>
                                        <li><a href="#">Vivamus - Condimentum gravida</a></li>
                                        <li><a href="#">Pellentesque - Condimentum gravida</a></li>
                                        <li><a href="#">Fusce vel - Condimentum gravida</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="panel">
                                    <h4><i class="icon-screenshot"></i> Subscribe</h4>

                                    <form />
                                        <label>Full Name</label>
                                        <input type="text" name="" value="" placeholder="Enter Your Full Name" required="" />
                                        <label>Email</label>
                                        <input type="email" name="" value="" placeholder="Enter Your Email" required="" />
                                        <div>
                                            <button class="btn-proper btn">Send</button>
                                        </div>



                                    </form>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="panel">
                                    <h4><i class="icon-trophy"></i> Recent News</h4>
                                    <ul class="unstyled list-link">
                                        <li><a href="#">Sed eu leo orci, condimentum gravida metus</a></li>
                                        <li><a href="#">Etiam at nulla ipsum, in rhoncus purus</a></li>
                                        <li><a href="#">Fusce vel magna faucibus felis dapibus facilisis</a></li>
                                        <li><a href="#">Vivamus scelerisque dui in massa</a></li>
                                        <li><a href="#">Pellentesque eget adipiscing dui semper</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="back-to-top" class="text-center"><a href="#"><i class="icon-angle-up"></i></a></div>
                </div>
                <div id="footer-twit" class="text-center">
                    <div class="container">
                        <div class="panel">
                            <p><i class="icon-twitter icon-4x"></i> <i class="icon-quote-left qoute"></i> Vivamus diam diam, fermentum sed dapibus eget, egestas sed eros. Lorem fermentum ipsum dolor sit amet, ipsum dolor sit amet ... <i class="icon-quote-right qoute"></i></p>
                        </div>
                    </div>
                </div>
                <div id="footer" class="text-center">
                    <div class="panel">
                        <p>Copyright &copy; <a href="#">Your Site</a> - <a href="index.html">Home</a> | <a href="about_us.html">About Us</a> | <a href="faq.html">FAQ</a> | <a href="contact.html">Contact Us</a> | <a href="career.html">Career</a></p>
                    </div>
                </div>
            </div><!-- end  Footer -->
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
